spring.application.name=court-booking
spring.datasource.url=jdbc:mysql://localhost:3306/court_booking
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=tajnyKlucMusiByCoNajmenej32ZnakovDlhyInakToSpadne